### ISSUE TITLE
SmartThings motion and multipurpose (door) sensors don't unpair with Digi Xstick

### ISSUE THREAD

**Issue by kgiori** [WebThingsIO/zigbee-adapter#54]
I have two different RPi+Digi Xstick units. The SmartThings door and motion sensors were paired with one of them. After following the unpair procedure, I can pair them again with the same Xstick but they are not recognized (not discovered during scan) by the other Xstick, even if the other RPi unit is off. If I swap the Xstick dongles in the RPis, the pairing follows the dongle, as we would expect. The two unpair procedures tried were:

1. pull battery, reinsert with button pressed. little LED is green until button release and then periodically blinks blue. when scan to pair again succeeds, LED blinks a few times green.
2. hold down reset button (LED green) until flashes red a couple times briefly, then goes into blinky blue state. pairing success causes LED to blink green a couple times.

Using Zigbee adapter 0.5.6 and gateway 0.6-pre1.

**Comment by dhylands** [comment]
I'm not surprised. The gateway sends out the unpair command, but battery powered devices aren't listenng,  so it gets lost.

The only way to make the unpair work is to wait until the battery powered devices does its periodic checkin and then send the unpair command.

Since the unpair command is missed, you need to factory reset the battery powered devices to re-pair them with a different dongle.
